---
- name: Chustomise Ubuntu
  become: false
  when: ansible_env.RUNTIME != "docker"
  block:
    - name: Update dock position
      ansible.builtin.shell:
        cmd: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
