---
- name: Check if Conda is installed
  become: false
  stat:
    path: "{{ ansible_env.HOME }}/miniconda/bin/conda"
  register: conda_installed

- name: Install Miniconda
  become: true
  when: not conda_installed.stat.exists
  block:
    - name: Download Miniconda installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/miniconda-installer.sh
        mode: '0755'

    - name: Install Miniconda
      shell: bash /tmp/miniconda-installer.sh -b -p $HOME/miniconda
      args:
        executable: /bin/bash
      environment:
        HOME: "{{ ansible_env.HOME }}"

    - name: Initialize Miniconda for Zsh
      shell: "{{ ansible_env.HOME }}/miniconda/bin/conda init zsh"
      args:
        executable: /bin/zsh

    - name: Conda autoactivate base
      shell: "source conda {{ ansible_env.HOME }}/.zshrc && config --set auto_activate_base true"

    - name: Remove Miniconda installer script
      file:
        path: /tmp/miniconda-installer.sh
        state: absent