- name: Configure Ubuntu
  hosts: all

  pre_tasks:
    - name: System details
      debug: msg="{{ item }}"
      with_items:
        - "Release: {{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }}"
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False

  tasks:
    # Base system
    - include_tasks: tasks/base_system/zsh.yml
    - include_tasks: tasks/base_system/main-packages.yml
    - include_tasks: tasks/base_system/neovim.yml
    - include_tasks: tasks/base_system/starship.yml

    # Software
    - include_tasks: tasks/software/miniconda.yml
    - include_tasks: tasks/software/golang.yml

    # providers
    - include_tasks: tasks/providers/terraform.yml
    - include_tasks: tasks/providers/aws.yml
    - include_tasks: tasks/providers/gcloud.yml
    # - include_tasks: tasks/providers/rust.yml

    - include_tasks: tasks/customizations/update_visuals.yml

  post_tasks:
    - name: Dist-upgrade
      become: true
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      become: true
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: true
      apt:
        autoremove: yes
